config/routes.rb
Rails.application.routes.draw do
  resources :projects

  resources :users

  resources :categories

  get 'site/about'

  resources :profiles

  get 'site/home'

   root 'site#home'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :title, :body


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all.paginate(page: params[:page], per_page: 5)
  #  @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:title, :body, :created_at, :updated_at, :url, :location, :username, :user_id, :image_url, :suspended_at, :suspension_status)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile, html: {class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :created_at %>
    <%= f.input :updated_at %>
    <%= f.input :url %>
    <%= f.input :location %>
    <%= f.input :user_id %>
    <%= f.input :image_url %>
    <%= f.input :suspended_at %>
    <%= f.input :suspension_status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class = "container"

<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

</div>

app/views/profiles/index.html.erb
<div class = "container">
<h1>Michigan Avenue Profiles</h1>

<p>Share something you've experienced or a memory associated with Michigan Avenue, and read other people's stories.</p>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @profiles.each do |profile| %>
      <tr>
        <td><%= link_to profile.title, profile %></td>
      </tr>
    <% end %>

     </tbody>
</table>
<%= will_paginate @profiles %>
<br>

<%= link_to 'New Profile', new_profile_path %>
</div>

app/views/profiles/new.html.erb
<div class = "container"

<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

</div>

app/views/profiles/show.html.erb
<div class = "container">

<p id="notice"><%= notice %></p>

<div>
<h1>
  <%= @profile.title %>
</h1>
</div>

<div>
<p>
   <%= textilize @profile.body %>
</p>
</div>
<div>
<% unless @profile.url == nil || "" %>
    <p>Read more about this story at: <a href="<%= @profile.url %>"><%= profile.url %></p>
  <% end %>
</div>

<div>
 <p>
  <strong>Location:</strong>
  <%= @profile.location %>
 </p>
</div>

 <p>
   <strong>User:</strong>
    <%= @profile.user_id %>
 </p>


<div>
<% unless @profile.image_url == nil || "" %>
    "<%= profile.image_url %></p>
  <% end %>
</div>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

</div>